### ISSUE TITLE
Please add necessary instructions for utils

### ISSUE THREAD

**Issue by Yanfors** [shrimonmuke0202/AlpaPICO#1]
I got the following error when running the code
```
Traceback (most recent call last):
  File "/root/AlpaPICO/train_instruct.py", line 19, in <module>
    from utils.instruct_dataset import InstructDataset, Instruction
ModuleNotFoundError: No module named 'utils.instruct_dataset'
```

**Comment by sree181** [comment]
Any updates on this?

**Comment by sree181** [comment]
> Any updates on this?
The instruct modules are these or extensions of these 
https://github.com/poteminr/instruct-ner/tree/adbb1bb32d08835f5c14fe3e2ca02d298ba252c0/instruction_ner/utils . Secondly this git is not the reflecting what authors have claimed in paper .

**Comment by shrimonmuke0202** [comment]
Sorry for the late reply. I have included all the necessary files used to train the model and predict the results present in the paper. Please use metric.py to predict the results. We use https://github.com/XZhang97666/AlpaCare to train our model with train_instruct.sh and inference_instruct_vllm.py. Please follow Readme.

**Comment by sree181** [comment]
> Sorry for the late reply. I have included all the necessary files used to train the model and predict the results present in the paper. Please use metric.py to predict the results. We use https://github.com/XZhang97666/AlpaCare to train our model with train_instruct.sh and inference_instruct_vllm.py.

Thank you appreciate your help and  for the quick reply
